### ISSUE TITLE
Investigate outstanding requests

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1072]
(1) Imported but missing CMO Sample Name: 14956_B, 07027_BC, 05971_CD, and 15201_D (from Danielle), 14470_F (from Maria), 14214_D (from Pav). Could this issue been caused by the label generator being offline due to the prod issues? How do we generate the labels after they've been imported into SMILE?

(2) Stack trace shows 500 server error when manually imported `13670_F`
```
2024-01-02 14:36:45.081 ERROR 46512 --- [lTaskExecutor-3] o.m.s.p.p.limsrest.LimsRequestUtil       : Error encountered during attempt to fetch sample manifest for '13670_F_7', request url: 'https://igolims.mskcc.org:8443/LimsRest/api/getSampleManifest?igoSampleId=13670_F_7'

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [{"timestamp":"2024-01-02T19:36:45.095+00:00","status":500,"error":"Internal Server Error","path":"/LimsRest/api/getSampleManifest"}]
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:100) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:583) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.mskcc.smile.publisher.pipeline.limsrest.LimsRequestUtil.getSampleManifest(LimsRequestUtil.java:180) ~[classes!/:0.0.1-SNAPSHOT]
	at org.mskcc.smile.publisher.pipeline.limsrest.LimsRequestUtil$$FastClassBySpringCGLIB$$dceefdd8.invoke(<generated>) [classes!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[na:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_372]

2024-01-02 14:36:45.083  WARN 46512 --- [lTaskExecutor-1] o.m.s.p.p.limsrest.LimsRequestProcessor  : Encountered error during attempt to fetch sample manifest for sample: 13670_F_7

java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_372]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[na:1.8.0_372]
	at org.mskcc.smile.publisher.pipeline.limsrest.LimsRequestProcessor.process(LimsRequestProcessor.java:62) [classes!/:0.0.1-SNAPSHOT]
	at org.mskcc.smile.publisher.pipeline.limsrest.LimsRequestProcessor.process(LimsRequestProcessor.java:21) [classes!/:0.0.1-SNAPSHOT]
	at org.mskcc.smile.publisher.pipeline.limsrest.LimsRequestProcessor$$FastClassBySpringCGLIB$$b134747c.invoke(<generated>) [classes!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.mskcc.smile.publisher.pipeline.limsrest.LimsRequestProcessor$$EnhancerBySpringCGLIB$$9da69535.process(<generated>) [classes!/:0.0.1-SNAPSHOT]
	at org.springframework.batch.integration.async.AsyncItemProcessor$1.call(AsyncItemProcessor.java:104) [spring-batch-integration-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372]
Caused by: java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[na:1.8.0_372]
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813) ~[na:1.8.0_372]
	at java.util.Arrays.asList(Arrays.java:3800) ~[na:1.8.0_372]
	at org.mskcc.smile.publisher.pipeline.limsrest.LimsRequestUtil.getSampleManifest(LimsRequestUtil.java:189) ~[classes!/:0.0.1-SNAPSHOT]
	at org.mskcc.smile.publisher.pipeline.limsrest.LimsRequestUtil$$FastClassBySpringCGLIB$$dceefdd8.invoke(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[na:1.8.0_372]
	... 3 common frames omitted

2024-01-02 14:36:45.105  WARN 46512 --- [           main] o.m.s.p.p.limsrest.LimsRequestListener   : Encountered errors while fetching from LimsRest - see report summary for details

ERROR SUMMARY REPORT BY REQUEST
	--> Total number of requests with errors: 1

Request: 13670_F, errors: 1
	Errors during sample manifest fetch: 13670_F_7

2024-01-02 14:36:45.106  INFO 46512 --- [           main] o.s.batch.core.step.AbstractStep         : Step: [limsRequestPublisherStep] executed in 2s371ms
```

**Comment by ao508** [comment]
Update: these have been imported but the samples didn't get labels generated for them due to `isCmoRequest:false` - waiting for confirmation from Tim that this is the only data value that needs changing so that we can update the data ourselves and import these requests.
