### ISSUE TITLE
Request 16567 missing from SMILE. 

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1338]

**Comment by qu8n** [comment]
This request failed to pass through the `label-generator`. Based on the stack trace below, looks like the error came from the `generateValidationReport` function inside `CmoLabelGeneratorServiceImpl.java`, specifically this line:
```java
Map<String, Object> sampleStatusMap = mapper.convertValue(sampleMap.get("status"), Map.class);
```
I think this line expected the sample's `status` to be a map structure but instead got the stringified version.

As a fix, what do you think of a handler like below that handles different types of the sample's status?
```java
Map<String, Object> sampleStatusMap;
Object statusObj = sampleMap.get("status");
if (statusObj instanceof String) {
    sampleStatusMap = mapper.readValue((String) statusObj, Map.class);
} else {
    sampleStatusMap = mapper.convertValue(statusObj, Map.class);
}
```

### Stack trace (of `label-generator`)
```bash
[smile@plvicmosmile1 ~]$ podman logs -f label-generator | grep -A 25 16567
2024-11-26T03:43:45.569Z  INFO 1 --- [pool-2-thread-1] s.s.i.LabelGenMessageHandlingServiceImpl : Extracting samples from request received: 16567
2024-11-26T03:43:45.571Z  INFO 1 --- [pool-2-thread-3] s.s.i.LabelGenMessageHandlingServiceImpl : Publishing request to: MDB_STREAM.server.igo-new-request
2024-11-26T03:43:48.808Z  WARN 1 --- [pool-2-thread-1] o.m.s.s.i.CmoLabelGeneratorServiceImpl   : Skipping patient sample with null CMO sample label: CMO patient ID = C-CWEP59, sample primary ID = 16261_1
2024-11-26T03:43:48.808Z  INFO 1 --- [pool-2-thread-1] s.s.i.LabelGenMessageHandlingServiceImpl : Changes detected in CMO sample label metadata - updating sample CMO label to newly generated label: 16567_2, new label: C-CWEP59-X003-d03
2024-11-26T03:43:48.815Z ERROR 1 --- [pool-2-thread-1] s.s.i.LabelGenMessageHandlingServiceImpl : Error during request handling

java.lang.IllegalArgumentException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"fastQs":"missing","igoComplete":"false"}')
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4624) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4555) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	at org.mskcc.smile.service.impl.CmoLabelGeneratorServiceImpl.generateValidationReport(CmoLabelGeneratorServiceImpl.java:627) ~[!/:0.1.0]
	at org.mskcc.smile.service.impl.LabelGenMessageHandlingServiceImpl$CmoLabelGeneratorHandler.run(LabelGenMessageHandlingServiceImpl.java:319) ~[!/:0.1.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"fastQs":"missing","igoComplete":"false"}')
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1754) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1379) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:454) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4619) ~[jackson-databind-2.17.2.jar!/:2.17.2]
	... 6 common frames omitted
```

**Comment by ao508** [comment]
technically this should always be a string actually so I'll adjust the code to treat it as such. thanks for catching this!
