### ISSUE TITLE
CVR DMP requeue/consume and backfill for SMILE

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#647]
Update:

Got this stack trace on the prod machine that did not get thrown on the dev machine but using the sample publisher to pub dmp clinical sample messages to smile.

Will try to split the file up into batches of ~1,000 samples? Also will need to look into why the queue is full as well because nothing obvious stood out in the `nats-jetstream` docker logs.

```
java.lang.IllegalStateException: Output queue is full 0
	at io.nats.client.impl.MessageQueue.push(MessageQueue.java:124) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.MessageQueue.push(MessageQueue.java:110) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsConnectionWriter.queue(NatsConnectionWriter.java:208) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsConnection.queueOutgoing(NatsConnection.java:1313) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsConnection.sendSubscriptionMessage(NatsConnection.java:919) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsConnection.createSubscription(NatsConnection.java:892) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsDispatcher.subscribeImpl(NatsDispatcher.java:258) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsDispatcher.subscribeReturningSubscription(NatsDispatcher.java:202) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsConnection.request(NatsConnection.java:1030) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsConnection.request(NatsConnection.java:979) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsJetStream.makeRequestResponseRequired(NatsJetStream.java:630) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsJetStream.publishSync(NatsJetStream.java:324) ~[jnats-2.10.0.jar!/:2.10.0]
	at io.nats.client.impl.NatsJetStream.publish(NatsJetStream.java:260) ~[jnats-2.10.0.jar!/:2.10.0]
	at org.mskcc.cmo.messaging.impl.JSGatewayImpl$NATSPublisher.run(JSGatewayImpl.java:269) ~[smile-messaging-java-1.3.2.RELEASE.jar!/:0.0.1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_322]
```

```
Before we begin.. 
- How many samples are there?
- Confirm what time the fetches begin with pipelines team. 
- Decide on batch size to work with for backfilling. 
- Measure the time it takes [cmo-pipelines/import-scripts/cvr_dmp_endpoint_utility.py](https://github.com/knowledgesystems/cmo-pipelines/blob/master/import-scripts/cvr_dmp_endpoint_utility.py) to requeue samples and write the `cvr_data.json` to the file system, followed by the consume/publish job by the CVR fetcher
```

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/647?planning-poker) with ZenHub @divyamadala30

**Comment by ao508** [comment]
possible demo: show a subset of patients with both clinical and research samples
