### ISSUE TITLE
Unrecognized field "standard_coverage" in DMP sample metadata

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#671]
Unrecognized field `standard_coverage` in DMP sample metadata is throwing an exception when handling samples received on `DMP_NEW_SAMPLE` topic. 

Done condition:
- This field is added to the JSON java model `DmpSampleMetadata` schema
- When constructing a new instance of `SmileSample` & `SampleMetadata` from `DmpSampleMetadata`, add `standard_coverage` and its value as a key-value pair in the `SampleMetadata` "additionalProperties" map

stack trace in `cmo-metadb` docker log

```
2022-04-30 06:53:23.906  INFO 1 --- [        nats:13] s.s.i.ClinicalMessageHandlingServiceImpl : Received message on topic: MDB_STREAM.server.dmp-new-sample
2022-04-30 06:53:23.908 ERROR 1 --- [        nats:13] s.s.i.ClinicalMessageHandlingServiceImpl : Exception during processing of new clinical sample on topic: MDB_STREAM.server.dmp-new-sample

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "standard_coverage" (class org.mskcc.smile.model.dmp.DmpSampleMetadata), not marked as ignorable (36 known properties: "dmp_sample_so_id", "tumor_type_code", "dmp_alys_task_name", "msi-type", "msi-score", "cbx_sample_id", "legacy_patient_id", "gene-panel", "dmp_patient_id", "tmb_cohort_percentile", "dmp_alys_task_id", "msi-comment", "dmp_sample_id", "legacy_sample_id", "cbx_patient_id", "tmb_score", "sample_coverage", "tumor_type_name", "alys2sample_id", "metastasis_site", "tmb_tt_percentile", "somatic_status", "is_metastasis", "outside_institute", "date_tumor_sequencing", "gender", "linked_mskimpact_case", "tumor_purity", "retrieve_status", "biopsy_site", "consent-parta", "consent-partc", "primary_site", "so_comments", "so_status_name", "slide-viewer-id"])
 at [Source: (String)"{"alys2sample_id":135472,"cbx_patient_id":72209,"cbx_sample_id":117653,"date_tumor_sequencing":"Fri, 22 Apr 2022 16:40:03 GMT","dmp_alys_task_id":9943,"dmp_alys_task_name":"ACCESSv1-CLIN-20220054","dmp_patient_id":"P-0078427","dmp_sample_id":"P-0078427-T01-XS1","dmp_sample_so_id":122856,"gender":0,"gene-panel":"ACCESS129","is_metastasis":1,"metastasis_site":"Not available","msi-comment":"NA","msi-score":"-1","msi-type":"NA","outside_institute":"MSKCC","primary_site":"Pancreas","retrieve_status":"[truncated 420 chars]; line: 1, column: 765] (through reference chain: org.mskcc.smile.model.dmp.DmpSampleMetadata["standard_coverage"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at org.mskcc.smile.service.impl.ClinicalMessageHandlingServiceImpl$1.onMessage(ClinicalMessageHandlingServiceImpl.java:243) ~[service-0.1.0.jar!/:0.1.0]
	at org.mskcc.cmo.messaging.impl.JSGatewayImpl.onMessage(JSGatewayImpl.java:218) [smile-messaging-java-1.3.2.RELEASE.jar!/:0.0.1-SNAPSHOT]
	at org.mskcc.cmo.messaging.impl.JSGatewayImpl.lambda$subscribe$0(JSGatewayImpl.java:182) [smile-messaging-java-1.3.2.RELEASE.jar!/:0.0.1-SNAPSHOT]
	at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:98) ~[jnats-2.10.0.jar!/:2.10.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_312]
```

**Comment by ao508** [comment]
Draft PR https://github.com/mskcc/smile-server/pull/679
