### ISSUE TITLE
BUG: Updates to sample that also includes a CMO patient ID swap 

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#700]
Scenario:
- Existing sample (`sample-1-a`) in SMILE with CMO patient ID `CMOPT-A`
- Request with updates for `sample-1-a` that includes changes to cmoSampleClass (Normal --> Unknown Tumor) and CMO Patient ID (CMOPT-A --> CMOPT-X)

This existing sample has updates that (1) affect the CMO label and (2) the updates also include a CMO patient ID swap and (3) the CMO patient ID that it is being swapped to does not already exist in the database.

Also for consideration: If going through the sample update workflow - if a sample. update includes a cmo patient id swap then should we update the sample-patient relationship for that single sample being updated or should _all_ samples linked to the former patient id _also_ be swapped to whatever the new patient id is (i.e., from CMOPT-A --> CMOPT-X)

**Comment by divyamadala30** [comment]
Error while updating cmoPatientId through topic `MDB_STREAM.server.consistency-checker.igo-new-request`: 
```
java.lang.NullPointerException: null
	at org.mskcc.smile.model.web.PublishedSmileSample.<init>(PublishedSmileSample.java:74) ~[model-0.1.0.jar!/:0.1.0]
	at org.mskcc.smile.service.impl.SampleServiceImpl.getPublishedSmileSample(SampleServiceImpl.java:190) ~[service-0.1.0.jar!/:0.1.0]
	at org.mskcc.smile.service.impl.SampleServiceImpl$$FastClassBySpringCGLIB$$574c27ef.invoke(<generated>) ~[service-0.1.0.jar!/:0.1.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.mskcc.smile.service.impl.SampleServiceImpl$$EnhancerBySpringCGLIB$$8f47d87a.getPublishedSmileSample(<generated>) ~[service-0.1.0.jar!/:0.1.0]
	at org.mskcc.smile.service.impl.RequestServiceImpl.getPublishedSmileRequestById(RequestServiceImpl.java:165) ~[service-0.1.0.jar!/:0.1.0]
	at org.mskcc.smile.service.impl.RequestServiceImpl$$FastClassBySpringCGLIB$$84e33762.invoke(<generated>) ~[service-0.1.0.jar!/:0.1.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.mskcc.smile.service.impl.RequestServiceImpl$$EnhancerBySpringCGLIB$$ba4cc6b3.getPublishedSmileRequestById(<generated>) ~[service-0.1.0.jar!/:0.1.0]
	at org.mskcc.smile.service.impl.ResearchMessageHandlingServiceImpl$IgoRequestHandler.run(ResearchMessageHandlingServiceImpl.java:134) ~[service-0.1.0.jar!/:0.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271]
```
